name = "DocSeeker"
uuid = "33d173f1-3be9-53c5-a697-8225b67db89c"
version = "0.3.2"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Hiccup = "9fb69e20-1954-56bb-a84f-559cc56a8ff7"
Juno = "e5e0dc1b-0480-54bc-9374-aad01c23163d"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
StringDistances = "88034a9c-02f8-509d-84a9-84ec65e18404"
URIParser = "30578b45-9adc-5946-b283-645ec420af67"

[compat]
Requires = "0.5.2, 1.0"
StringDistances = "0.4.0"
julia = "0.7, 1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
